version: '2'
services:
  web:
    restart: always
    image: giorg/php:latest
    container_name: web
    volumes_from:
      - web-data
    depends_on:
      - mysql
      - mongo
      - memcached
      - web-data
    ports:
      - "80:80"
    environment:
      - ALLOW_OVERRIDE=true
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "web"
  web-data:
    image: busybox
    container_name: web-data
    volumes:
      - ~/www:/var/www
  mysql:
    restart: always
    image: mariadb
    container_name: mysql
    depends_on:
      - mysql-data
      - elasticsearch
      - kibana
      - logstash
    volumes_from:
      - mysql-data
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASS=root
      - MYSQL_PASSWORD=root
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "mysql"
  mysql-data:
    image: busybox
    container_name: mysql-data
    volumes:
      - /var/lib/boot2docker/mysql:/var/lib/mysql
  mongo:
    restart: always
    image: mongo:2.4.14
    container_name: mongo
    depends_on:
      - mongo-data
    volumes_from:
      - mongo-data
    ports:
      - "27017:27017"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "mongo"
  mongo-data:
    image: busybox
    container_name: mongo-data
    volumes:
      - /var/lib/boot2docker/mongo/data/db:/data/db
  mongoexpress:
    restart: always
    image: knickers/mongo-express
    container_name: mongoexpress
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  solr:
    restart: always
    image: giorg/solr:5.3.0
    container_name: solr
    volumes_from:
      - solr-data
    ports:
      - "8983:8983"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "solr"
  solr-data:
    image: busybox
    container_name: solr-data
    volumes:
      - ~/www/solr/server/solr/:/opt/solr/server/solr/
  memcached:
    restart: always
    image: memcached
    container_name: memcached
    ports:
      - "11211:11211"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "memcached"
  mail:
    restart: always
    image: djfarrelly/maildev
    container_name: mail
    depends_on:
      - web
    ports:
      - "1080:80"
  phpmyadmin:
    restart: always
    image: dnhsoft/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8001:80"
    environment:
      - DBHOST=mysql
      - DBUSER=root
      - DBPASS=root
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "phpmyadmin"
  elasticsearch:
    restart: always
    image: elasticsearch:latest
    container_name: elasticsearch
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    restart: always
    image: giorg/logstash:latest
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "12201:12201"
      - "12201:12201/udp"
    links:
      - elasticsearch
  kibana:
    restart: always
    image: giorg/kibana:latest
    container_name: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch