solr5:
  extends:
    file: ../common/docker-compose.yml
    service: solr5
  volumes:
    - /var/lib/boot2docker/data/ggiordana/solr/solr/server/solr/configsets:/opt/solr-5.3.0/server/solr/configsets
    - /var/lib/boot2docker/data/ggiordana/solr/solr/server/solr/eshops:/opt/solr-5.3.0/server/solr/eshops
solr3:
  extends:
    file: ../common/docker-compose.yml
    service: solr3
  volumes:
    - /var/lib/boot2docker/data/ggiordana/solr/trunk/theoz:/opt/apache-solr-3.6.1/theoz
  links:
    - db:db
web:
  extends:
      file: ../common/docker-compose.yml
      service: web
  volumes:
#    - /Users/Guillaume/.n98-magerun:/var/www/.n98-magerun/scripts
    - /var/lib/boot2docker/data/apache/30-custom.ini:/etc/php5/apache2/conf.d/30-custom.ini
    - /var/lib/boot2docker/data/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
  volumes_from:
    - data-web
  links:
    - db:db
    - mail:mail
    - memcached:memcached
    - solr3:solr3
    - solr5:solr5
    - pma:pma
data-web:
  extends:
    file: ../common/docker-compose.yml
    service: data-web
  volumes:
    - /var/lib/boot2docker/data/ggiordana/www:/var/www
data-db:
  extends:
    file: ../common/docker-compose.yml
    service: data-db
db:
  extends:
    file: ../common/docker-compose.yml
    service: db
  volumes_from:
      - data-db
memcached:
  extends:
    file: ../common/docker-compose.yml
    service: memcached
mail:
  extends:
    file: ../common/docker-compose.yml
    service: mail
pma:
  extends:
    file: ../common/docker-compose.yml
    service: pma
  links:
    - db:db
