pma:
  restart: always
  image: dnhsoft/phpmyadmin:4.3.6
  ports:
    - "8001:80"
  environment:
    - DBHOST=db
    - DBUSER=root
    - DBPASS=root
data-db:
  image: busybox
  volumes :
    - /var/lib/boot2docker/mysql:/var/lib/mysql
data-web:
  image: busybox
db:
  restart: always
  image: percona:5.5
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_PASS=root
    - MYSQL_PASSWORD=root
memcached:
  restart: always
  image: memcached
  ports:
    - "11211:11211"
mail:
  restart: always
  image: djfarrelly/maildev
  ports:
    - "1080:80"
solr5:
  restart: always
  image: giorg/solr:5.3.0
  ports:
    - "8984:8983"
solr3:
  restart: always
  image: giorg/solr:3.6.1
  ports:
    - "8983:8983"
web:
  restart: always
  build: web
  ports:
    - "80:80"
  environment:
    - ALLOW_OVERRIDE=true
