pma:
  restart: always
  image: dnhsoft/phpmyadmin:4.3.6
  ports:
    - "8001:80"
  environment:
    - DBHOST=db
    - DBUSER=root
    - DBPASS=root
db:
  restart: always
  image: percona:5.5
  volumes:
    - /var/lib/boot2docker/mysql:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_PASS=root
    - MYSQL_PASSWORD=root
memcached:
  restart: always
  image: memcached
  ports:
    - "11211:11211"
mail:
  restart: always
  image: djfarrelly/maildev
  ports:
    - "1080:80"
solr5:
  restart: always
  build: solr5
  ports:
    - "8984:8984"
solr3:
  restart: always
  build: solr3
  ports:
    - "8983:8983"
web:
  restart: always
  build: web
  ports:
    - "80:80"
  environment:
    - ALLOW_OVERRIDE=true
